"""
PDF generation using ReportLab — pure Python, no system dependencies.
"""
import io
from datetime import datetime
from typing import TYPE_CHECKING

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from documents import DISCLAIMER, JURISDICTION_CITATIONS, PROVINCE_NAMES

if TYPE_CHECKING:
    from schema import Corporation

NAVY = colors.HexColor("#1A3A6B")
GREY = colors.HexColor("#666666")
LIGHT_GREY = colors.HexColor("#888888")
TABLE_HEADER_BG = colors.HexColor("#E8EEF7")


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Title"], textColor=NAVY, fontSize=18, spaceAfter=6, alignment=TA_CENTER),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], textColor=NAVY, fontSize=13, spaceAfter=4, alignment=TA_CENTER),
        "h3": ParagraphStyle("h3", parent=base["Heading3"], textColor=NAVY, fontSize=11, spaceAfter=4),
        "body": ParagraphStyle("body", parent=base["Normal"], fontSize=10, spaceAfter=6, leading=14),
        "citation": ParagraphStyle("citation", parent=base["Normal"], fontSize=8, textColor=GREY, alignment=TA_CENTER, spaceAfter=12, fontName="Helvetica-Oblique"),
        "disclaimer": ParagraphStyle("disclaimer", parent=base["Normal"], fontSize=7, textColor=LIGHT_GREY, alignment=TA_CENTER, spaceBefore=20),
        "center": ParagraphStyle("center", parent=base["Normal"], fontSize=10, alignment=TA_CENTER, spaceAfter=6),
        "bold": ParagraphStyle("bold", parent=base["Normal"], fontSize=10, fontName="Helvetica-Bold", spaceAfter=4),
        "toc": ParagraphStyle("toc", parent=base["Normal"], fontSize=10, spaceAfter=8, leftIndent=20),
    }


def _today():
    return datetime.utcnow().strftime("%B %d, %Y")


def _fiscal_display(fiscal_year_end: str) -> str:
    try:
        return datetime.strptime(fiscal_year_end, "%Y-%m-%d").strftime("%B %d")
    except Exception:
        return fiscal_year_end or "December 31"


def _table_style():
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_BG),
        ("TEXTCOLOR", (0, 0), (-1, 0), NAVY),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFF")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ])


def _sig_block(name: str, role: str) -> list:
    s = _styles()
    return [
        Spacer(1, 0.3 * inch),
        HRFlowable(width=2.5 * inch, thickness=0.5, color=colors.black),
        Paragraph(f"{name}<br/>{role}", s["body"]),
        Spacer(1, 0.15 * inch),
    ]


def generate_minute_book_pdf(docs: dict, corp: "Corporation" = None) -> bytes:
    """Generate a complete minute book PDF using ReportLab."""
    if corp is None:
        # Fallback — shouldn't happen in normal flow
        buf = io.BytesIO()
        buf.write(b"%PDF-1.4\n% fallback\n")
        return buf.getvalue()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=1 * inch,
        rightMargin=1 * inch,
        topMargin=1 * inch,
        bottomMargin=1 * inch,
    )

    s = _styles()
    province_name = PROVINCE_NAMES.get(corp.province, corp.province)
    citation = JURISDICTION_CITATIONS.get(corp.province, "Applicable legislation")
    today = _today()
    fiscal = _fiscal_display(corp.fiscal_year_end)
    officer_name = corp.officers[0].name if corp.officers else (corp.directors[0].name if corp.directors else "[Officer]")

    story = []

    # ── COVER PAGE ──────────────────────────────────────
    story += [
        Spacer(1, 1.5 * inch),
        Paragraph("MINUTE BOOK", ParagraphStyle("cover_title", fontSize=28, textColor=NAVY, alignment=TA_CENTER, fontName="Helvetica-Bold")),
        Spacer(1, 0.3 * inch),
        Paragraph(corp.corp_name.upper(), ParagraphStyle("corp", fontSize=18, textColor=NAVY, alignment=TA_CENTER, fontName="Helvetica-Bold")),
        Spacer(1, 0.15 * inch),
        Paragraph(f"{province_name} Corporation", s["center"]),
        Paragraph(f"Corporation No. {corp.corp_number or '[To be inserted]'}", s["center"]),
        Paragraph(f"Incorporated: {corp.incorporation_date or '[Date]'}", s["center"]),
        Spacer(1, 1.5 * inch),
        Paragraph(f"Generated by CorpMinute.ca &nbsp;|&nbsp; {today}", ParagraphStyle("gen", fontSize=8, textColor=LIGHT_GREY, alignment=TA_CENTER)),
        PageBreak(),
    ]

    # ── TABLE OF CONTENTS ────────────────────────────────
    story.append(Paragraph("TABLE OF CONTENTS", s["title"]))
    story.append(Spacer(1, 0.2 * inch))
    toc_items = [
        "1.  Annual Directors' Resolution",
        "2.  Annual Shareholders' Resolution",
        "3.  Register of Directors",
        "4.  Register of Officers",
        "5.  Register of Shareholders",
        "6.  Share Ledger",
        "7.  Consent to Act as Director",
        "8.  Organizational Resolution",
        "9.  Banking Resolution",
    ]
    for item in toc_items:
        story.append(Paragraph(item, s["toc"]))
        story.append(HRFlowable(width="100%", thickness=0.3, color=colors.HexColor("#DDDDDD")))
    story.append(PageBreak())

    # ── DOC 1: DIRECTORS RESOLUTION ─────────────────────
    story += [
        Paragraph(corp.corp_name.upper(), s["title"]),
        Paragraph("ANNUAL RESOLUTION OF THE DIRECTORS", s["h2"]),
        Paragraph(f"{province_name} Corporation &nbsp;|&nbsp; {citation}", s["citation"]),
        Paragraph(
            f"The undersigned, being all of the directors of {corp.corp_name} (the \"Corporation\"), "
            f"hereby consent to the passing of the following resolution in lieu of a meeting, "
            f"pursuant to {citation}:", s["body"]),
        Spacer(1, 0.1 * inch),
        Paragraph("RESOLVED THAT:", s["bold"]),
        Paragraph(f"1. The financial statements of the Corporation for the fiscal year ended "
                  f"<b>{fiscal}</b> are hereby approved and adopted.", s["body"]),
        Paragraph("2. The audit of the financial statements is hereby waived for the current "
                  "fiscal year, as permitted by the applicable corporations legislation.", s["body"]),
        Paragraph("3. The current officer(s) of the Corporation are hereby confirmed in their "
                  "respective roles until the next annual meeting of the directors or until "
                  "their successors are duly appointed.", s["body"]),
        Paragraph("4. The directors are hereby authorized to transact all business of the "
                  "Corporation in the ordinary course.", s["body"]),
        Spacer(1, 0.2 * inch),
        Paragraph(f"DATED this {today}.", s["body"]),
    ]
    for d in corp.directors:
        story += _sig_block(d.name, "Director")
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))
    story.append(PageBreak())

    # ── DOC 2: SHAREHOLDERS RESOLUTION ──────────────────
    story += [
        Paragraph(corp.corp_name.upper(), s["title"]),
        Paragraph("ANNUAL RESOLUTION OF THE SHAREHOLDERS", s["h2"]),
        Paragraph(f"{province_name} Corporation &nbsp;|&nbsp; {citation}", s["citation"]),
        Paragraph(
            f"The undersigned, being all of the shareholders of {corp.corp_name} entitled to vote, "
            f"hereby consent to the passing of the following resolution in lieu of a meeting, "
            f"pursuant to {citation}:", s["body"]),
        Spacer(1, 0.1 * inch),
        Paragraph("RESOLVED THAT:", s["bold"]),
        Paragraph("1. The current director(s) of the Corporation are hereby re-elected to hold "
                  "office until the next annual meeting of shareholders or until their successors "
                  "are duly elected or appointed.", s["body"]),
        Paragraph("2. The appointment of an auditor is hereby waived for the current fiscal year, "
                  "as all shareholders have consented to such waiver in accordance with the "
                  "applicable corporations legislation.", s["body"]),
        Paragraph("3. Any one director or officer is hereby authorized to execute and deliver "
                  "all documents necessary to give effect to the foregoing resolutions.", s["body"]),
        Spacer(1, 0.2 * inch),
        Paragraph(f"DATED this {today}.", s["body"]),
    ]
    for sh in corp.shareholders:
        story += _sig_block(sh.name, f"Shareholder ({sh.quantity} {sh.share_class} shares)")
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))
    story.append(PageBreak())

    # ── DOC 3: REGISTER OF DIRECTORS ────────────────────
    story += [
        Paragraph(corp.corp_name.upper(), s["title"]),
        Paragraph("REGISTER OF DIRECTORS", s["h2"]),
        Paragraph(f"{province_name} &nbsp;|&nbsp; {citation} &nbsp;|&nbsp; Last updated: {today}", s["citation"]),
    ]
    dir_data = [["Full Name", "Residential Address", "Date Appointed", "Date Ceased"]]
    dir_data += [[d.name, d.address, d.appointed, ""] for d in corp.directors] or [["—", "—", "—", "—"]]
    story.append(Table(dir_data, colWidths=[1.5*inch, 2.5*inch, 1.2*inch, 1.2*inch], style=_table_style()))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))
    story.append(PageBreak())

    # ── DOC 4: REGISTER OF OFFICERS ─────────────────────
    story += [
        Paragraph(corp.corp_name.upper(), s["title"]),
        Paragraph("REGISTER OF OFFICERS", s["h2"]),
        Paragraph(f"{province_name} &nbsp;|&nbsp; {citation} &nbsp;|&nbsp; Last updated: {today}", s["citation"]),
    ]
    off_rows = [[o.name, o.role, o.appointed, ""] for o in corp.officers]
    if not off_rows and corp.directors:
        off_rows = [[corp.directors[0].name, "President and Secretary", corp.incorporation_date or today, ""]]
    off_data = [["Full Name", "Office Held", "Date Appointed", "Date Ceased"]] + (off_rows or [["—", "—", "—", "—"]])
    story.append(Table(off_data, colWidths=[1.8*inch, 2.2*inch, 1.2*inch, 1.2*inch], style=_table_style()))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))
    story.append(PageBreak())

    # ── DOC 5: REGISTER OF SHAREHOLDERS ─────────────────
    story += [
        Paragraph(corp.corp_name.upper(), s["title"]),
        Paragraph("REGISTER OF SHAREHOLDERS", s["h2"]),
        Paragraph(f"{province_name} &nbsp;|&nbsp; {citation} &nbsp;|&nbsp; Last updated: {today}", s["citation"]),
    ]
    sh_data = [["Full Name / Entity", "Share Class", "Shares Held", "Address"]]
    sh_data += [[sh.name, sh.share_class, str(sh.quantity), ""] for sh in corp.shareholders] or [["—", "—", "—", "—"]]
    story.append(Table(sh_data, colWidths=[2*inch, 1.2*inch, 1.2*inch, 2*inch], style=_table_style()))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))
    story.append(PageBreak())

    # ── DOC 6: SHARE LEDGER ──────────────────────────────
    story += [
        Paragraph(corp.corp_name.upper(), s["title"]),
        Paragraph("SHARE LEDGER", s["h2"]),
        Paragraph(f"{province_name} &nbsp;|&nbsp; Last updated: {today}", s["citation"]),
    ]
    led_data = [["Certificate #", "Shareholder", "Class", "Shares", "Date Issued"]]
    led_data += [
        [f"C-{i:04d}", sh.name, sh.share_class, str(sh.quantity), corp.incorporation_date or today]
        for i, sh in enumerate(corp.shareholders, 1)
    ] or [["—", "—", "—", "—", "—"]]
    story.append(Table(led_data, colWidths=[1*inch, 2*inch, 1*inch, 1*inch, 1.4*inch], style=_table_style()))
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))
    story.append(PageBreak())

    # ── DOC 7: ORGANIZATIONAL RESOLUTION ────────────────
    story += [
        Paragraph(corp.corp_name.upper(), s["title"]),
        Paragraph("ORGANIZATIONAL RESOLUTION OF THE DIRECTORS", s["h2"]),
        Paragraph(f"{province_name} Corporation &nbsp;|&nbsp; {citation}", s["citation"]),
        Paragraph(f"The directors of {corp.corp_name} hereby pass the following organizational "
                  f"resolution in lieu of an organizational meeting, pursuant to {citation}:", s["body"]),
        Spacer(1, 0.1 * inch),
        Paragraph("RESOLVED THAT:", s["bold"]),
        Paragraph(f"1. <b>{officer_name}</b> is hereby appointed President and Secretary of the Corporation.", s["body"]),
        Paragraph(f"2. The fiscal year of the Corporation shall end on <b>{fiscal}</b> of each year.", s["body"]),
        Paragraph("3. The Corporation is hereby authorized to open one or more bank accounts and "
                  "to conduct banking business as the directors may determine.", s["body"]),
        Paragraph("4. The by-laws of the Corporation, if any, are hereby confirmed and adopted.", s["body"]),
        Paragraph("5. Any director or officer is authorized to execute documents necessary to "
                  "complete the organization of the Corporation.", s["body"]),
        Spacer(1, 0.2 * inch),
        Paragraph(f"DATED this {today}.", s["body"]),
    ]
    for d in corp.directors:
        story += _sig_block(d.name, "Director")
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))
    story.append(PageBreak())

    # ── DOC 8: BANKING RESOLUTION ────────────────────────
    story += [
        Paragraph(corp.corp_name.upper(), s["title"]),
        Paragraph("BANKING RESOLUTION OF THE DIRECTORS", s["h2"]),
        Paragraph(f"{province_name} Corporation &nbsp;|&nbsp; {citation}", s["citation"]),
        Paragraph(f"The directors of {corp.corp_name} hereby resolve as follows:", s["body"]),
        Spacer(1, 0.1 * inch),
        Paragraph("RESOLVED THAT:", s["bold"]),
        Paragraph("1. The Corporation is hereby authorized to open and maintain one or more bank "
                  "accounts at such financial institution(s) as the directors may determine.", s["body"]),
        Paragraph(f"2. <b>{officer_name}</b>, or such other persons as the directors may designate, "
                  "are hereby authorized to operate such bank accounts, including signing cheques, "
                  "making electronic transfers, and executing any documentation required by the "
                  "financial institution.", s["body"]),
        Paragraph("3. The financial institution is hereby authorized to honour all cheques, drafts, "
                  "and orders signed by the authorized signatories.", s["body"]),
        Paragraph("4. A copy of this resolution, certified by any director or officer, shall "
                  "constitute sufficient authority for any financial institution to act upon.", s["body"]),
        Spacer(1, 0.2 * inch),
        Paragraph(f"DATED this {today}.", s["body"]),
    ]
    for d in corp.directors:
        story += _sig_block(d.name, "Director")
    story.append(Paragraph(DISCLAIMER, s["disclaimer"]))

    # ── CONSENT TO ACT AS DIRECTOR (one page per director) ──
    for d in corp.directors:
        story.append(PageBreak())
        story += [
            Paragraph(corp.corp_name.upper(), s["title"]),
            Paragraph("CONSENT TO ACT AS DIRECTOR", s["h2"]),
            Paragraph(f"{province_name} Corporation &nbsp;|&nbsp; {citation}", s["citation"]),
            Paragraph(
                f"I, <b>{d.name}</b>, of {d.address}, hereby consent to act as a director of "
                f"{corp.corp_name}, a corporation incorporated under the laws of {province_name}, "
                f"pursuant to {citation}.", s["body"]),
            Spacer(1, 0.2 * inch),
            Paragraph(f"DATED this {today}.", s["body"]),
        ]
        story += _sig_block(d.name, "Director")
        story.append(Paragraph(DISCLAIMER, s["disclaimer"]))

    doc.build(story)
    return buf.getvalue()


def docx_to_pdf_bytes(doc, corp=None) -> bytes:
    """Convert a single document to PDF. Uses corp context if available."""
    if corp is not None:
        return generate_minute_book_pdf({}, corp=corp)
    # Fallback: extract text and render simple PDF
    from reportlab.platypus import SimpleDocTemplate, Paragraph
    from reportlab.lib.styles import getSampleStyleSheet
    buf = io.BytesIO()
    pdf = SimpleDocTemplate(buf, pagesize=letter)
    styles = getSampleStyleSheet()
    story = [Paragraph(p.text, styles["Normal"]) for p in doc.paragraphs if p.text.strip()]
    pdf.build(story)
    return buf.getvalue()
